/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component.lapHoaDon;
//https://www.youtube.com/watch?v=RMwufjRRHBU&t=442s

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Virtue Nguyen
 */
public class CustomButtonChucNang extends javax.swing.JPanel {

    /**
     * Creates new form CustomButtonChucNang
     */
    public CustomButtonChucNang() {
        initComponents();
    }
    public void initEvent(TableEvent event,int row){
        cmDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmDelete = new dev.skyherobrine.app.views.dashboard.component.lapHoaDon.ButtonChucNang();

        cmDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgIconLapHoaDon/delete.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cmDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cmDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dev.skyherobrine.app.views.dashboard.component.lapHoaDon.ButtonChucNang cmDelete;
    // End of variables declaration//GEN-END:variables
}
