/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component.quanLyNhapHang;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Virtue Nguyen
 */
public class PanelAction1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction1() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent1 event, int row) {
        cmdDuyet.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDuyet(row);
            }
        });
        cmdHuy.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onHuy(row);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdDuyet = new dev.skyherobrine.app.views.dashboard.component.quanLyNhapHang.ActionButton1();
        cmdHuy = new dev.skyherobrine.app.views.dashboard.component.quanLyNhapHang.ActionButton1();

        cmdDuyet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgIconQuanLyNhapHang/duyet.png"))); // NOI18N

        cmdHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgIconQuanLyNhapHang/huy.png"))); // NOI18N
        cmdHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dev.skyherobrine.app.views.dashboard.component.quanLyNhapHang.ActionButton1 cmdDuyet;
    private dev.skyherobrine.app.views.dashboard.component.quanLyNhapHang.ActionButton1 cmdHuy;
    // End of variables declaration//GEN-END:variables
}
