/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
import dev.skyherobrine.app.controllers.dashboardui.person.KhachHangController;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class KhachHangGUI extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public KhachHangGUI() {
        initComponents();
        new KhachHangController(this).loaddsKhachHang();
        new KhachHangController(this).loadComboBoxPhanThongTinNV();
        new KhachHangController(this).loadComboBoxPhanTimKiem();
        tbDanhSachKhachHang.addMouseListener(new KhachHangController(this));
        btnThemKhachHang.addActionListener(new KhachHangController(this));
        btnSuaKhachHang.addActionListener(new KhachHangController(this));
        btnXoaKhachHang.addActionListener(new KhachHangController(this));

        cbTkGioiTinhKhachHang.addActionListener(new KhachHangController(this));
        jDateChooserTkNgaySinh.addPropertyChangeListener(new KhachHangController(this));
        txtTuKhoaTimKiem.addKeyListener(new KhachHangController(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new javax.swing.JPanel();
        pnThongTinKhachHang = new javax.swing.JPanel();
        lbMaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        lbHoTenKhachHang = new javax.swing.JLabel();
        txtHoTenKhachHang = new javax.swing.JTextField();
        lbGIoiTinhKhachHang = new javax.swing.JLabel();
        lbSoDienThoaiKhachHang = new javax.swing.JLabel();
        txtSoDienThoaiKhachHang = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtDiemTichLuy = new javax.swing.JTextField();
        lbNgaySinhKhachHang = new javax.swing.JLabel();
        btnSuaKhachHang = new javax.swing.JButton();
        btnThemKhachHang = new javax.swing.JButton();
        btnXoaKhachHang = new javax.swing.JButton();
        cbGioiTinh = new javax.swing.JComboBox<>();
        cbGioiTinh.setEnabled(false);
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        jDateChooserNgaySinh.setEnabled(false);
        pnDanhSachKhachHang = new javax.swing.JPanel();
        spDanhSachKhachHang = new javax.swing.JScrollPane();
        tbDanhSachKhachHang = new javax.swing.JTable();
        pnTimKiemKhachHang = new javax.swing.JPanel();
        cbTkGioiTinhKhachHang = new javax.swing.JComboBox<>();
        lbTkTenKhachHang = new javax.swing.JLabel();
        txtTuKhoaTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserTkNgaySinh = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnThongTinKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTinKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbMaKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMaKhachHang.setText("Mã khách hàng:");

        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaKhachHang.setEnabled(false);
        txtMaKhachHang.setPreferredSize(new java.awt.Dimension(64, 25));

        lbHoTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHoTenKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHoTenKhachHang.setText("Họ tên:");

        txtHoTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoTenKhachHang.setEnabled(false);
        txtHoTenKhachHang.setPreferredSize(new java.awt.Dimension(64, 25));

        lbGIoiTinhKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGIoiTinhKhachHang.setText("Giới tính:");

        lbSoDienThoaiKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSoDienThoaiKhachHang.setText("Số điện thoại:");

        txtSoDienThoaiKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoDienThoaiKhachHang.setEnabled(false);
        txtSoDienThoaiKhachHang.setPreferredSize(new java.awt.Dimension(79, 33));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("Điểm tích luỹ:");

        txtDiemTichLuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiemTichLuy.setEnabled(false);

        lbNgaySinhKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgaySinhKhachHang.setText("Ngày Sinh:");

        btnSuaKhachHang.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnSuaKhachHang.setText("Sửa khách hàng");

        btnThemKhachHang.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnThemKhachHang.setText("Thêm khách hàng");

        btnXoaKhachHang.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnXoaKhachHang.setText("Xoá khách hàng");

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnThongTinKhachHangLayout = new javax.swing.GroupLayout(pnThongTinKhachHang);
        pnThongTinKhachHang.setLayout(pnThongTinKhachHangLayout);
        pnThongTinKhachHangLayout.setHorizontalGroup(
            pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoDienThoaiKhachHang)
                                    .addComponent(lbNgaySinhKhachHang))
                                .addGap(25, 25, 25)
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbMaKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnThemKhachHang)))
                .addGap(156, 156, 156)
                .addComponent(btnSuaKhachHang)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbHoTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHoTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbGIoiTinhKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnXoaKhachHang)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        pnThongTinKhachHangLayout.setVerticalGroup(
            pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGIoiTinhKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNgaySinhKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiemTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEmail))
                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKhachHang)
                    .addComponent(btnSuaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhachHang))
                .addGap(36, 36, 36))
        );

        pnDanhSachKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnDanhSachKhachHang.setLayout(new java.awt.BorderLayout());

        tbDanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số điện thoại", "Giới tính", "Ngày sinh", "Điểm tích lũy"
            }
        ));
        spDanhSachKhachHang.setViewportView(tbDanhSachKhachHang);

        pnDanhSachKhachHang.add(spDanhSachKhachHang, java.awt.BorderLayout.CENTER);

        pnTimKiemKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        cbTkGioiTinhKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkGioiTinhKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giới tính", "Nam", "Nữ", "Gay", "Les", " " }));

        lbTkTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTkTenKhachHang.setText("Từ khoá tìm kiếm:");

        txtTuKhoaTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ngày sinh:");

        javax.swing.GroupLayout pnTimKiemKhachHangLayout = new javax.swing.GroupLayout(pnTimKiemKhachHang);
        pnTimKiemKhachHang.setLayout(pnTimKiemKhachHangLayout);
        pnTimKiemKhachHangLayout.setHorizontalGroup(
            pnTimKiemKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemKhachHangLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(cbTkGioiTinhKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addComponent(lbTkTenKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(137, 137, 137))
        );
        pnTimKiemKhachHangLayout.setVerticalGroup(
            pnTimKiemKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTkGioiTinhKhachHang)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTuKhoaTimKiem)
                .addComponent(lbTkTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnBGThongTinCaNhanLayout = new javax.swing.GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTimKiemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDanhSachKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnDanhSachKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pnThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKhachHang;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JButton btnXoaKhachHang;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbTkGioiTinhKhachHang;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private com.toedter.calendar.JDateChooser jDateChooserTkNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGIoiTinhKhachHang;
    private javax.swing.JLabel lbHoTenKhachHang;
    private javax.swing.JLabel lbMaKhachHang;
    private javax.swing.JLabel lbNgaySinhKhachHang;
    private javax.swing.JLabel lbSoDienThoaiKhachHang;
    private javax.swing.JLabel lbTkTenKhachHang;
    private javax.swing.JPanel pnBGThongTinCaNhan;
    private javax.swing.JPanel pnDanhSachKhachHang;
    private javax.swing.JPanel pnThongTinKhachHang;
    private javax.swing.JPanel pnTimKiemKhachHang;
    private javax.swing.JScrollPane spDanhSachKhachHang;
    private javax.swing.JTable tbDanhSachKhachHang;
    private javax.swing.JTextField txtDiemTichLuy;
    private javax.swing.JTextField txtHoTenKhachHang;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoDienThoaiKhachHang;
    private javax.swing.JTextField txtTuKhoaTimKiem;
    // End of variables declaration//GEN-END:variables

    public JTable getTbDanhSachKhachHang() {
        return tbDanhSachKhachHang;
    }
    public JButton getButtonThemKhachHang(){return btnThemKhachHang;}
    public JButton getButtonSuaKhachHang(){return btnSuaKhachHang;}
    public JButton getButtonXoaKhachHang(){return btnXoaKhachHang;}
    public JTextField getTxtMaKhachHang(){return txtMaKhachHang;}
    public JTextField getTxtSoDienThoaiKhachHang(){return txtSoDienThoaiKhachHang;}
    public JDateChooser getjDateChooserNgaySinhKhachHang(){return jDateChooserNgaySinh;}
    public JTextField getTxtHoTenKhachHang(){return txtHoTenKhachHang;}
    public JComboBox getCbGioiTinh(){return  cbGioiTinh;}
    public JTextField getTxtDiemTichLuy(){return txtDiemTichLuy;}
    public JComboBox getCbTkGioiTinh(){return cbTkGioiTinhKhachHang;}
    public JTextField getTxtTuKhoaTimKiem(){return txtTuKhoaTimKiem;}
    public JDateChooser getjDateChooserTkNgaySinh(){return jDateChooserTkNgaySinh;}
}
