/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class KhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public KhuyenMai() throws Exception{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new javax.swing.JPanel();
        pnDanhSachCacKhuyenMai = new javax.swing.JPanel();
        spDanhSachCacKhuyenMaiCuaSanPham = new javax.swing.JScrollPane();
        tbDanhSachCacKhuyenMaiCuaSanPham = new javax.swing.JTable();
        pnTimKiemKhuyenMai = new javax.swing.JPanel();
        txtTuKhoaTimKiemKhuyenMai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserNgayApDungTkKhuyenMai = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooserNgayHetHanTkKhuyenMai = new com.toedter.calendar.JDateChooser();
        pnThongTInKhuyenMai = new javax.swing.JPanel();
        lbMaKhuyenMai = new javax.swing.JLabel();
        lbTile = new javax.swing.JLabel();
        lbNgayApDung = new javax.swing.JLabel();
        lbNgayHetHan = new javax.swing.JLabel();
        lbTenSanPhamApDung = new javax.swing.JLabel();
        txtMaKhuyenMai = new javax.swing.JTextField();
        txtTile = new javax.swing.JTextField();
        txtTenKhuyenMai = new javax.swing.JTextField();
        btnThemKhuyenMai = new javax.swing.JButton();
        btnSuaKhuyenMai = new javax.swing.JButton();
        btnXoaKhuyenMai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserNgayApDungThongTinKhuyenMai = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayHetHanjThongTinKhuyenMai = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnDanhSachCacKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachCacKhuyenMai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh các khuyến mãi của sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachCacKhuyenMaiCuaSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDanhSachCacKhuyenMaiCuaSanPham.setViewportView(tbDanhSachCacKhuyenMaiCuaSanPham);

        javax.swing.GroupLayout pnDanhSachCacKhuyenMaiLayout = new javax.swing.GroupLayout(pnDanhSachCacKhuyenMai);
        pnDanhSachCacKhuyenMai.setLayout(pnDanhSachCacKhuyenMaiLayout);
        pnDanhSachCacKhuyenMaiLayout.setHorizontalGroup(
            pnDanhSachCacKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacKhuyenMaiCuaSanPham)
        );
        pnDanhSachCacKhuyenMaiLayout.setVerticalGroup(
            pnDanhSachCacKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacKhuyenMaiCuaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pnTimKiemKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemKhuyenMai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtTuKhoaTimKiemKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTuKhoaTimKiemKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuKhoaTimKiemKhuyenMaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Từ khoá tìm kiếm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ngày áp dụng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ngày hết hạn:");

        javax.swing.GroupLayout pnTimKiemKhuyenMaiLayout = new javax.swing.GroupLayout(pnTimKiemKhuyenMai);
        pnTimKiemKhuyenMai.setLayout(pnTimKiemKhuyenMaiLayout);
        pnTimKiemKhuyenMaiLayout.setHorizontalGroup(
            pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserNgayApDungTkKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserNgayHetHanTkKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTuKhoaTimKiemKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnTimKiemKhuyenMaiLayout.setVerticalGroup(
            pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimKiemKhuyenMaiLayout.createSequentialGroup()
                        .addGroup(pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserNgayApDungTkKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTuKhoaTimKiemKhuyenMai)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemKhuyenMaiLayout.createSequentialGroup()
                        .addGroup(pnTimKiemKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserNgayHetHanTkKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))))
        );

        pnThongTInKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTInKhuyenMai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khuyến mãi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        lbMaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaKhuyenMai.setText("Mã khuyến mãi:");

        lbTile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTile.setText("Tỉ lệ:");

        lbNgayApDung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgayApDung.setText("Ngày áp dụng:");

        lbNgayHetHan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgayHetHan.setText("Ngày hết hạn:");

        lbTenSanPhamApDung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenSanPhamApDung.setText("Tên khuyến mãi:");

        txtMaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTenKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnThemKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/plus.png"))); // NOI18N
        btnThemKhuyenMai.setText("Thêm khuyến mãi");

        btnSuaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/edit.png"))); // NOI18N
        btnSuaKhuyenMai.setText("Sửa khuyến mãi");

        btnXoaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/remove.png"))); // NOI18N
        btnXoaKhuyenMai.setText("Xoá khuyến mãi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("%");

        javax.swing.GroupLayout pnThongTInKhuyenMaiLayout = new javax.swing.GroupLayout(pnThongTInKhuyenMai);
        pnThongTInKhuyenMai.setLayout(pnThongTInKhuyenMaiLayout);
        pnThongTInKhuyenMaiLayout.setHorizontalGroup(
            pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTInKhuyenMaiLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTInKhuyenMaiLayout.createSequentialGroup()
                        .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTile)
                            .addGroup(pnThongTInKhuyenMaiLayout.createSequentialGroup()
                                .addComponent(lbMaKhuyenMai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(317, 317, 317)
                        .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgayHetHan)
                            .addComponent(lbNgayApDung)))
                    .addGroup(pnThongTInKhuyenMaiLayout.createSequentialGroup()
                        .addComponent(lbTenSanPhamApDung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTInKhuyenMaiLayout.createSequentialGroup()
                                .addComponent(txtTile, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserNgayApDungThongTinKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jDateChooserNgayHetHanjThongTinKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(245, 245, 245))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTInKhuyenMaiLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(btnThemKhuyenMai)
                .addGap(274, 274, 274)
                .addComponent(btnSuaKhuyenMai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaKhuyenMai)
                .addGap(265, 265, 265))
        );
        pnThongTInKhuyenMaiLayout.setVerticalGroup(
            pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInKhuyenMaiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNgayApDung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserNgayApDungThongTinKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDateChooserNgayHetHanjThongTinKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenSanPhamApDung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(pnThongTInKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout pnBGThongTinCaNhanLayout = new javax.swing.GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnTimKiemKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnThongTInKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDanhSachCacKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnDanhSachCacKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTInKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTuKhoaTimKiemKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuKhoaTimKiemKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuKhoaTimKiemKhuyenMaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKhuyenMai;
    private javax.swing.JButton btnThemKhuyenMai;
    private javax.swing.JButton btnXoaKhuyenMai;
    private com.toedter.calendar.JDateChooser jDateChooserNgayApDungThongTinKhuyenMai;
    private com.toedter.calendar.JDateChooser jDateChooserNgayApDungTkKhuyenMai;
    private com.toedter.calendar.JDateChooser jDateChooserNgayHetHanTkKhuyenMai;
    private com.toedter.calendar.JDateChooser jDateChooserNgayHetHanjThongTinKhuyenMai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbMaKhuyenMai;
    private javax.swing.JLabel lbNgayApDung;
    private javax.swing.JLabel lbNgayHetHan;
    private javax.swing.JLabel lbTenSanPhamApDung;
    private javax.swing.JLabel lbTile;
    private javax.swing.JPanel pnBGThongTinCaNhan;
    private javax.swing.JPanel pnDanhSachCacKhuyenMai;
    private javax.swing.JPanel pnThongTInKhuyenMai;
    private javax.swing.JPanel pnTimKiemKhuyenMai;
    private javax.swing.JScrollPane spDanhSachCacKhuyenMaiCuaSanPham;
    private javax.swing.JTable tbDanhSachCacKhuyenMaiCuaSanPham;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtTenKhuyenMai;
    private javax.swing.JTextField txtTile;
    private javax.swing.JTextField txtTuKhoaTimKiemKhuyenMai;
    // End of variables declaration//GEN-END:variables


    public JButton getBtnSuaKhuyenMai() {
        return btnSuaKhuyenMai;
    }

    public JButton getBtnThemKhuyenMai() {
        return btnThemKhuyenMai;
    }

    public JButton getBtnXoaKhuyenMai() {
        return btnXoaKhuyenMai;
    }

    public JTextField getTxtMaKhuyenMai() {
        return txtMaKhuyenMai;
    }

    public JTextField getTxtTenKhuyenMai() {
        return txtTenKhuyenMai;
    }

    public JTextField getTxtTile() {
        return txtTile;
    }

    public JDateChooser getjDateChooserNgayApDungThongTinKhuyenMai() {
        return jDateChooserNgayApDungThongTinKhuyenMai;
    }

    public JDateChooser getjDateChooserNgayHetHanjThongTinKhuyenMai() {
        return jDateChooserNgayHetHanjThongTinKhuyenMai;
    }
}
