/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import dev.skyherobrine.app.views.dashboard.component.lapHoaDon.TableCellEditor;
import dev.skyherobrine.app.views.dashboard.component.lapHoaDon.TableCellRenderer;
import dev.skyherobrine.app.views.dashboard.component.lapHoaDon.TableEvent;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author Virtue Nguyen
 */
public class LapHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public LapHoaDon() {
        initComponents();
        TableEvent event1 = new TableEvent() {
            @Override
            public void onDelete(int row) {
                if(tbDanhSachCacSanPhamTrongGioHang.isEditing()){
                    tbDanhSachCacSanPhamTrongGioHang.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel)tbDanhSachCacSanPhamTrongGioHang.getModel();
                model.removeRow(row);
                System.out.println("Bảng danh sách sản phẩm giỏ hàng. Xoá hàng ngang theo mảng: "+row);
            }
        };
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellRenderer(new TableCellRenderer());
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellEditor(new TableCellEditor(event1));
        
        TableEvent event2 = new TableEvent() {
            @Override
            public void onDelete(int row) {
                if(tbHoaDonLuuTam.isEditing()){
                    tbHoaDonLuuTam.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel)tbHoaDonLuuTam.getModel();
                model.removeRow(row);
                System.out.println("Bảng lưu hoá đơn tạm. Xoá hàng ngang theo mảng: "+row);
            }
        };
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellRenderer(new TableCellRenderer());
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellEditor(new TableCellEditor(event2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGLapHoaDon = new javax.swing.JPanel();
        pnTraiLapHoaDon = new javax.swing.JPanel();
        pnPhaiTrenLapHoaDon = new javax.swing.JPanel();
        txtTimKiemSanPham = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        spDanhSachCacSanPhamTrongGioHang = new javax.swing.JScrollPane();
        tbDanhSachCacSanPhamTrongGioHang = new javax.swing.JTable();
        pnPhaiDuoiLapHoaDon = new javax.swing.JPanel();
        pnCamera = new javax.swing.JPanel();
        pnHoaDonLuuTam = new javax.swing.JPanel();
        spHoaDonLuuTam = new javax.swing.JScrollPane();
        tbHoaDonLuuTam = new javax.swing.JTable();
        txtTimKiemHoaDonLuuTam = new javax.swing.JTextField();
        pnPhaiLapHoaDon = new javax.swing.JPanel();
        pnThongTinHoaDon = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnBGLapHoaDon.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnTraiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnPhaiTrenLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        txtTimKiemSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemSanPham.setText("Tìm kiếm sản phẩm");
        txtTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSanPhamActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các sản phẩm trong giỏ hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        spDanhSachCacSanPhamTrongGioHang.setBackground(new java.awt.Color(255, 255, 255));

        tbDanhSachCacSanPhamTrongGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Mã sản phẩm", "Tên sản phẩm", "Kích thước", "Số lượng", "Đơn giá", "Thành tiền", ""
            }
        ));
        tbDanhSachCacSanPhamTrongGioHang.setRowHeight(40);
        tbDanhSachCacSanPhamTrongGioHang.setSelectionBackground(new java.awt.Color(0, 255, 58));
        tbDanhSachCacSanPhamTrongGioHang.setSelectionForeground(new java.awt.Color(243, 7, 7));
        spDanhSachCacSanPhamTrongGioHang.setViewportView(tbDanhSachCacSanPhamTrongGioHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPhaiTrenLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiTrenLapHoaDon);
        pnPhaiTrenLapHoaDon.setLayout(pnPhaiTrenLapHoaDonLayout);
        pnPhaiTrenLapHoaDonLayout.setHorizontalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                        .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnPhaiTrenLapHoaDonLayout.setVerticalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiDuoiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnCamera.setBackground(new java.awt.Color(255, 255, 255));
        pnCamera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        javax.swing.GroupLayout pnCameraLayout = new javax.swing.GroupLayout(pnCamera);
        pnCamera.setLayout(pnCameraLayout);
        pnCameraLayout.setHorizontalGroup(
            pnCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        pnCameraLayout.setVerticalGroup(
            pnCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHoaDonLuuTam.setBackground(new java.awt.Color(255, 255, 255));
        pnHoaDonLuuTam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá đơn lưu tạm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbHoaDonLuuTam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Tên khách hàng", "Số điện thoại", ""
            }
        ));
        tbHoaDonLuuTam.setRowHeight(40);
        tbHoaDonLuuTam.setSelectionBackground(new java.awt.Color(0, 255, 91));
        tbHoaDonLuuTam.setSelectionForeground(new java.awt.Color(255, 0, 0));
        spHoaDonLuuTam.setViewportView(tbHoaDonLuuTam);

        javax.swing.GroupLayout pnHoaDonLuuTamLayout = new javax.swing.GroupLayout(pnHoaDonLuuTam);
        pnHoaDonLuuTam.setLayout(pnHoaDonLuuTamLayout);
        pnHoaDonLuuTamLayout.setHorizontalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        pnHoaDonLuuTamLayout.setVerticalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        txtTimKiemHoaDonLuuTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemHoaDonLuuTam.setText("Tìm kiếm hoá đơn lưu tạm");
        txtTimKiemHoaDonLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemHoaDonLuuTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPhaiDuoiLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiDuoiLapHoaDon);
        pnPhaiDuoiLapHoaDon.setLayout(pnPhaiDuoiLapHoaDonLayout);
        pnPhaiDuoiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemHoaDonLuuTam)
                    .addComponent(pnHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnPhaiDuoiLapHoaDonLayout.setVerticalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemHoaDonLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(pnCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTraiLapHoaDonLayout = new javax.swing.GroupLayout(pnTraiLapHoaDon);
        pnTraiLapHoaDon.setLayout(pnTraiLapHoaDonLayout);
        pnTraiLapHoaDonLayout.setHorizontalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPhaiTrenLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiDuoiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTraiLapHoaDonLayout.setVerticalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTraiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnPhaiTrenLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiDuoiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        javax.swing.GroupLayout pnThongTinHoaDonLayout = new javax.swing.GroupLayout(pnThongTinHoaDon);
        pnThongTinHoaDon.setLayout(pnThongTinHoaDonLayout);
        pnThongTinHoaDonLayout.setHorizontalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        pnThongTinHoaDonLayout.setVerticalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPhaiLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiLapHoaDon);
        pnPhaiLapHoaDon.setLayout(pnPhaiLapHoaDonLayout);
        pnPhaiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        pnPhaiLapHoaDonLayout.setVerticalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBGLapHoaDonLayout = new javax.swing.GroupLayout(pnBGLapHoaDon);
        pnBGLapHoaDon.setLayout(pnBGLapHoaDonLayout);
        pnBGLapHoaDonLayout.setHorizontalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnTraiLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBGLapHoaDonLayout.setVerticalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTraiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemHoaDonLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemHoaDonLuuTamActionPerformed
        if (txtTimKiemHoaDonLuuTam.getText().equalsIgnoreCase("Tìm kiếm hoá đơn lưu tạm")) {
        txtTimKiemHoaDonLuuTam.setText("");
        txtTimKiemHoaDonLuuTam.setForeground(Color.BLACK); // Đổi màu văn bản khi bắt đầu nhập
    }
    }//GEN-LAST:event_txtTimKiemHoaDonLuuTamActionPerformed

    private void txtTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSanPhamActionPerformed
        if(txtTimKiemSanPham.getText().equalsIgnoreCase("Tìm kiếm sản phẩm")){
            txtTimKiemSanPham.setText("");
            txtTimKiemSanPham.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTimKiemSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnBGLapHoaDon;
    private javax.swing.JPanel pnCamera;
    private javax.swing.JPanel pnHoaDonLuuTam;
    private javax.swing.JPanel pnPhaiDuoiLapHoaDon;
    private javax.swing.JPanel pnPhaiLapHoaDon;
    private javax.swing.JPanel pnPhaiTrenLapHoaDon;
    private javax.swing.JPanel pnThongTinHoaDon;
    private javax.swing.JPanel pnTraiLapHoaDon;
    private javax.swing.JScrollPane spDanhSachCacSanPhamTrongGioHang;
    private javax.swing.JScrollPane spHoaDonLuuTam;
    private javax.swing.JTable tbDanhSachCacSanPhamTrongGioHang;
    private javax.swing.JTable tbHoaDonLuuTam;
    private javax.swing.JTextField txtTimKiemHoaDonLuuTam;
    private javax.swing.JTextField txtTimKiemSanPham;
    // End of variables declaration//GEN-END:variables
}
